# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dialogue import Ui_Dialog
from gMail import Ui_MainWindowM
import os

class Ui_MainWindow(object):
    def openwindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openshare(self):
        self.window = QtWidgets.QMainWindow()
        self.ui =Ui_MainWindow()
        self.ui.setupUi(self.windowindow)
        self.window.show()


    def setupUi(self, MainWindow):
        self.x = True
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1450, 815)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 411))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/priyanshu/MartianChronicles/rover.jpg")) #update the location of the rover.jpg
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 411))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.openimg)
        self.pushButton_3.clicked.connect(self.next_img)
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.frame_4, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        #dialouge box push button
        self.pushButton = QtWidgets.QPushButton(self.frame, clicked = lambda: self.openwindow())
        self.pushButton.setMinimumSize(QtCore.QSize(550, 0))
        self.pushButton.setText("Get Image")
        self.pushButton.setIconSize(QtCore.QSize(1400, 50))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1450, 22))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        #share button 
        self.actionSHare = QtWidgets.QAction(MainWindow,)
        self.actionSHare.setObjectName("actionSHare")
        self.menuOptions.addAction(self.actionSHare)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def openimg(self):
        if self.x==True:
            self.filelist = ['/home/priyanshu/MartianChronicles/images/' + f for f in os.listdir('/home/priyanshu/MartianChronicles/images') if f.endswith(".jpg")]
            print(self.filelist)
            self.filecounter = 0
            self.current_file = self.filelist[self.filecounter]
        else:
            pass

        pixmap = QtGui.QPixmap(self.current_file)
        pixmap = pixmap.scaled(self.label.width(),self.label.height())
        self.label.setPixmap(pixmap)
        

    def next_img(self):
        self.filecounter = (self.filecounter + 1) % len(self.filelist)
        self.current_file = self.filelist[self.filecounter]
        pixmap = QtGui.QPixmap(self.current_file)
        pixmap = pixmap.scaled(self.label.width(),self.label.height()) 
        self.label.setPixmap(pixmap)
        self.x = False
            
            

    def prev_img(self):
        if self.filecounter != 0:
            self.filecounter -= 1
            self.filecounter = (self.filecounter + len(self.filelist)) % len(self.filelist)
            self.current_file = self.filelist[self.filecounter]
            pixmap = QtGui.QPixmap(self.current_file)
            pixmap = pixmap.scaled(self.label.width(),self.label.height()) 
            self.label.setPixmap(pixmap)
        else:
            
            self.counter = len(self.file_list)
            self.filecounter -= 1
            self.filecounter = (self.filecounter + len(self.filelist)) % len(self.filelist)
            self.current_file = self.file_list[self.filecounter]
            pixmap = QtGui.QPixmap(self.current_file)
            pixmap = pixmap.scaled(self.label.width(),self.label.height()) 
            self.label.setPixmap(pixmap)






















    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "<"))
        self.pushButton_3.setText(_translate("MainWindow", ">"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionSHare.setText(_translate("MainWindow", "Share"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
